
import 'package:flutter/cupertino.dart';
import 'package:flutter/services.dart';
import 'package:ox_common/component.dart';
import 'package:ox_common/navigator/page_router.dart';

enum OXPushPageType {
  slideToLeft,
  noAnimation,
  opacity,
  transparent,
  present,
}

enum OXStackPageOption {
  reset,
  push,
  pop,
  replace
}

class OXNavigator extends Navigator {

  static final GlobalKey<NavigatorState> navigatorKey = new GlobalKey<NavigatorState>();

  static List<NavigatorObserver> observer = [];

  static RouteObserver routeObserver = RouteObserver();

  static bool canPop(BuildContext context) {
    return Navigator.canPop(context);
  }

  static BuildContext get rootContext => navigatorKey.currentContext!;

  @optionalTypeArgs
  static void pop<T extends Object?>(BuildContext? context, [T? result]) {
    context ??= navigatorKey.currentContext;
    if (context == null) return ;

    // Remove the current focus
    FocusScope.of(context).unfocus();

    if (canPop(context)) {
      Navigator.pop(context, result);
    } else {
      if (CupertinoSheetRoute.hasParentSheet(context)) {
        CupertinoSheetRoute.popSheet(context);
        return ;
      }
      SystemNavigator.pop();
    }
  }

  /// Flutter stack
  static void popToRoot<T extends Object>(BuildContext context) {
    // Remove the current focus
    FocusScope.of(context).unfocus();

    final navigator = Navigator.of(context, rootNavigator: true);
    if (navigator.canPop()) {
      navigator.popUntil((Route<dynamic> route) {
        return route.isFirst;
      });
    }
  }

  /// Pop to a specific page (currently only supported within the Flutter stack)
  /// pageType: The 'runtimeType.toString' of the page, which is used to simply specify the pop of the page
  /// pageId: Specified pageId, used for more complex navigation pops to a designated page. The pageId is generated by the designated page itself
  static void popToPage<T extends Object>(BuildContext context,
      {String? pageType, Object? pageId, isPrepage = false}) {
    assert(() {
      if (pageType == null && pageId == null) {
        throw FlutterError('The OXNavigator.popToPage method requires at least one of the parameters: pageType or pageId.');
      }
      return true;
    }());
    // Remove the current focus
    FocusScope.of(context).unfocus();
    bool isFindPage = false;
    int prepage = 0;
    Navigator.popUntil(context, (Route<dynamic> route) {
      bool checkPageType = true;
      OXRouteSettings? settings;
      try {
        settings = route.settings as OXRouteSettings;
      } catch (_) {}

      if (pageType != null && !isFindPage) {
        checkPageType = settings?.name == pageType;
        isFindPage = checkPageType;
      }
      bool checkPageId = true;
      if (pageId != null && !isFindPage) {
        checkPageId = settings?.pageId == pageId;
        isFindPage = checkPageId;
      }
      final bool isTargetPage = isPrepage ? (prepage == 1) && (checkPageType && checkPageId) : checkPageType && checkPageId;
      if (isFindPage) {
        prepage = 1;
      }
      return isTargetPage || route.isFirst;
    });
  }

  static void close(BuildContext context) {
    // Remove the current focus
    FocusScope.of(context).unfocus();
    SystemNavigator.pop();
  }

  @optionalTypeArgs
  static Future<T?> _push<T extends Object?>(
      BuildContext context, Route<T> route, [bool rootNavigator = false]) {
    _pushPreHandle(context);

    return Navigator.of(context, rootNavigator: rootNavigator).push(route);
  }

  static void _pushPreHandle(BuildContext context) {
    final currentSettings = ModalRoute.of(context)?.settings;
    if (currentSettings is! OXRouteSettings) return;

    if (currentSettings.isShortLived) {
      Navigator.pop(context);
    }
  }

  static Future<T?> pushReplacement<T extends Object?, TO extends Object?>(
      BuildContext context, Widget page, {
        String? pageName,
        Object? pageId,
        bool? isShortLived,
        TO? result,
      }) {
    return Navigator.pushReplacement<T, TO>(
      context,
      generalPageRouter(
        pageName: pageName,
        pageId: pageId,
        isShortLived: isShortLived,
        builder: (_) => page,
      ),
      result: result,
    );
  }

  @optionalTypeArgs
  static Future<T?> pushPage<T extends Object?>(
      BuildContext? context,
      WidgetBuilder builder, {
        String? pageName,
        Object? pageId,
        bool? isShortLived,
        bool fullscreenDialog = false,
        OXPushPageType type = OXPushPageType.slideToLeft,
      }) {
    context ??= navigatorKey.currentContext;
    if (context == null) return Future.value(null);

    pageName ??= builder(context).runtimeType.toString();

    final routeSettings = OXRouteSettings(
      name: pageName,
      pageId: pageId,
      isShortLived: isShortLived,
    );
    TransitionRoute<T> route;

    bool rootNavigator = false;
    switch (type) {
      case OXPushPageType.slideToLeft:
        route = SlideLeftToRightRoute<T>(
          fullscreenDialog: fullscreenDialog,
          settings: routeSettings,
          builder: builder,
        );
      case OXPushPageType.noAnimation:
        route = NoAnimationPageRoute<T>(
          builder: builder,
          settings: routeSettings,
        );
      case OXPushPageType.opacity:
        route = OpacityAnimationPageRoute<T>(
          builder: builder,
          settings: routeSettings,
        );
      case OXPushPageType.transparent:
        route = TransparentPageRoute<T>(
          builder: builder,
          settings: routeSettings,
        );
      case OXPushPageType.present:
        if (PlatformStyle.isUseMaterial || fullscreenDialog) {
          route = generalPageRouter<T>(
            builder: builder,
            pageName: pageName,
            pageId: pageId,
            isShortLived: isShortLived,
            fullscreenDialog: true,
          );
        } else {
          rootNavigator = true;
          route = OXCupertinoSheetRoute<T>(
            builder: builder,
            settings: routeSettings,
          );
        }
    }

    return OXNavigator._push(
      context,
      route,
      rootNavigator,
    );
  }

  static PageRoute<T> generalPageRouter<T>({
    required WidgetBuilder builder,
    String? pageName,
    Object? pageId,
    bool? isShortLived,
    fullscreenDialog = false,
  }) {
    return SlideLeftToRightRoute<T>(
      fullscreenDialog: fullscreenDialog,
      settings: OXRouteSettings(
        name: pageName,
        pageId: pageId,
        isShortLived: isShortLived,
      ),
      builder: builder,
    );
  }

  static bool isCurrentPage(BuildContext context) {
    return ModalRoute.of(context)?.isCurrent ?? false;
  }
}

class OXRouteSettings extends RouteSettings {
  const OXRouteSettings({
    super.name,
    this.pageId,
    bool? isShortLived,
  }) : isShortLived = isShortLived ?? false;

  final Object? pageId;
  final bool isShortLived;
}
